### PR TITLE
Fixes #63 - Avoid the javax.jms.IllegalStateException with SOLR index.

### LINKED ISSUE #63: Inspect and fix the javax.jms.IllegalStateException with SOLR index request
### Descriptive summary
Inspect and fix the issue of javax.jms.IllegalStateException that cause the failure of adding items for SOLR index.
See @rstanonik's comment on slack dams channel:
```
I see the following errors in the lib-hydratail-staging tomcat log
Server: Apache-Coyote/1.1; Content-Type: application/json; Content-Length: 292; Date: Tue, 10 Jul 2018 14:58:07 GMT; Connection: close; {"request":"\/objects\/bd8723769x\/index","queueSuccess":1,"message":"Indexing failures.","priority":"4","queueTotal":1,"errors":["Error sending object to queue: javax.jms.IllegalStateException: The Session is closed"],"statusCode":500,"timestamp":"2018-07-10T07:58:07-0700","status":"ERROR"}
2018-07-10 07:58:07,259 INFO edu.ucsd.library.xdre.utils.DAMSClient: POST https://lib-hydratail-staging.ucsd.edu:8443/dams/api/objects/bd8723769x/index?format=json&ts=dams&priority=4&user=lsitu&client=Custom+2.64-0-g7a43f64d2d2bb36c58e3f5e7ec4fd9b37094a5d7: ERROR status code 500. Error Indexing failures.
java.io.IOException: POST https://lib-hydratail-staging.ucsd.edu:8443/dams/api/objects/bd8723769x/index?format=json&ts=dams&priority=4&user=lsitu&client=Custom+2.64-0-g7a43f64d2d2bb36c58e3f5e7ec4fd9b37094a5d7: ERROR status code 500. Error Indexing failures.
2018-07-10 07:58:07,259 ERROR edu.ucsd.library.xdre.collection.CollectionHandler: SOLR update failed for bd8723769x: POST https://lib-hydratail-staging.ucsd.edu:8443/dams/api/objects/bd8723769x/index?format=json&ts=dams&priority=4&user=lsitu&client=Custom+2.64-0-g7a43f64d2d2bb36c58e3f5e7ec4fd9b37094a5d7: ERROR status code 500. Error Indexing failures.
```
### Rationale
This happened several times in the past when damsmanager requested SOLR, which caused solr not being updated for the objects ingested or edited.

### PR DESCRIPTION
**Pull request by lsitu**
Fixes #63 

Updated to avoid the javax.jms.IllegalStateException found during SOLR index request.

@ucsdlib/developers

### CODE REVIEW

File: src/java/edu/ucsd/library/dams/api/DAMSAPIServlet.java [hunk 1]
```diff
@@ -3733,28 +3723,55 @@ private String indexQueue( String objid, String type, int priority )
...
+						// re-initialize the JMS session.
+						initJmsSession(queueUrl, queueName);
+					}
+					catch (JMSException e)
+					{
+						log.error( "Error sending event to queue", e );
+						error = "Error sending object to queue: " + e.toString();
+					}
+				}
+			} while (++numOfTry < MAX_INDEX_TRY);
```
Comment (mcritchlow) [inline src/java/edu/ucsd/library/dams/api/DAMSAPIServlet.java:3775]: This code seems to run the `do/while` loop twice regardless of success with the first run through the `try` block. Is that correct? And if so, is that what we want? I suppose I would have imagined that upon a successful message send where no error is caught, the do/while loop would exit. But I may be reading this wrong.

Comment (lsitu) [reply src/java/edu/ucsd/library/dams/api/DAMSAPIServlet.java:3775]: @mcritchlow Good catch! It's corrected in commit https://github.com/ucsdlib/damsrepo/pull/64/commits/299da8880b36c8c1f2dab8e87f9df9a1bdcea640 now. Thanks.
